@accessToken={{refresh.response.body.$.access_token}}

### Get access token
# @name login
POST {{$dotenv KEYCLOAK_URL}}/realms/{{$dotenv KEYCLOAK_REALM}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv KEYCLOAK_CLIENT_ID}}
&client_secret={{$dotenv KEYCLOAK_CLIENT_SECRET}}
&grant_type=password
&username={{$dotenv KEYCLOAK_USERNAME}}
&password={{$dotenv KEYCLOAK_PASSWORD}}
&scope=roles

### Refresh token
# @name refresh
POST {{$dotenv KEYCLOAK_URL}}/realms/{{$dotenv KEYCLOAK_REALM}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv KEYCLOAK_CLIENT_ID}}
&client_secret={{$dotenv KEYCLOAK_CLIENT_SECRET}}
&grant_type=refresh_token
&refresh_token={{login.response.body.$.refresh_token}}

### Example
GET http://localhost:8080/
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8080/api/frame.jpeg?src=cctvId
Authorization: Bearer {{accessToken}}
